### ISSUE TITLE
ロゴ　オブジェ作成　

### ISSUE THREAD

**Issue by AtsukoWakamatsu** [furuhashilab/2020_TEDxdesign#1]

**Comment by Babby168** [comment]
[TEDxAoyamagakuinU_styly_object.zip](https://github.com/furuhashilab/2020_TEDxdesign/files/4851571/TEDxAoyamagakuinU_styly_object.zip)

![image](https://user-images.githubusercontent.com/40033443/86122821-66b2fb80-bb13-11ea-89bb-0479df01dbe7.png)

**Comment by cancancanda** [comment]
Blenderで作った３Dデータはglb(gITF)形式でエクスポートするとうまくいくことが多いっぽいです。これでSTYLYに取り込んでも色が付きました。
〈glb(glTF)は効率的で相互運用可能なアセット配布フォーマットとなることを意図しているフォーマットでBlenderでも最近サポートされたとのことです〉
[tedxaoyamagakuinu_styly_object.zip](https://github.com/furuhashilab/2020_TEDxdesign/files/4895051/tedxaoyamagakuinu_styly_object.zip)
