### ISSUE TITLE
stylyにクロマキー合成

### ISSUE THREAD

**Issue by AtsukoWakamatsu** [furuhashilab/2020_TEDxdesign#12]

**Comment by rensanrenren** [comment]
定点カメラなら違和感なく作れそうです
![image](https://user-images.githubusercontent.com/49857703/88639770-1c17a580-d0f8-11ea-8f10-4834ac528a1b.png)

**Comment by Babby168** [comment]
## 馬場作　試作動画
https://youtu.be/NmvggszVCmY

![PreTEDx](https://user-images.githubusercontent.com/40033443/88565257-483b1400-d06f-11ea-89a5-02edc13b55f7.PNG)
