### ISSUE TITLE
styly にTEDの動画を埋め込む

### ISSUE THREAD

**Issue by AtsukoWakamatsu** [furuhashilab/2020_TEDxdesign#13]

**Comment by AtsukoWakamatsu** [comment]
<img width="900" alt="スクリーンショット 2020-07-24 19 11 00" src="https://user-images.githubusercontent.com/40018174/88381570-9dfa8c80-cde1-11ea-8178-6fab21874cd1.png">

[styly](https://gallery.styly.cc/scene/03fc495d-26db-445d-b2b8-342bdbc1838d)

・めっちゃ簡単です
・空間に入ることはできるから雰囲気は悪くない
・ただ動画は二次元だからあんまり空間を作り込む意味はなくなりそう
・体全体を撮るようにして動きを大切にしたら悪くはないかも？

**Comment by Babby168** [comment]
STYLY上でのデフォルトの選択肢から選んでyoutube上の動画を差し込める

動画の再生・停止などの操作は不可

分かりやすく映るのは、[Curved Screen]での差し込み
（動画上の立体感は皆無...）

Rotating...系のものはなぜか映らない

![2020-07-24](https://user-images.githubusercontent.com/40033443/88384910-46abea80-cde8-11ea-9788-a64a4daf4af7.png)

[STYLYリンク](https://gallery.styly.cc/scene/22e1713a-d7eb-480e-9a1c-124396f1cb94)

**Comment by Babby168** [comment]
自分で作成した３Dオブジェクトに画像だったり、動画を貼り付けられる。

https://styly.cc/ja/tips/acceptance-webeditor/

**Comment by Babby168** [comment]
360°動画を挿入
https://styly.cc/ja/tips/styly-360movie-import/

![2020-07-24 (1)](https://user-images.githubusercontent.com/40033443/88386900-4d3c6100-cdec-11ea-9a5d-4ad0df23a6cc.png)

**Comment by AtsukoWakamatsu** [comment]
## 360度動画を入れてみた
・YouTubeにアップロードされている360度カメラのスピーチ映像みたけどかなり画質荒くなる。
・音質は割れない程度、よくもない
・人が動くとどうなるか別の動画で試してみる
・
<img width="754" alt="スクリーンショット 2020-07-26 3 07 42" src="https://user-images.githubusercontent.com/40018174/88463422-aa6c0b80-ceed-11ea-9772-f0079dc6c276.png">

[360度動画　styly](https://gallery.styly.cc/scene/7bf34c54-f261-4178-8577-fa5a87b14d2c)
