### ISSUE TITLE
7月ハッカソン　状況

### ISSUE THREAD

**Issue by AtsukoWakamatsu** [furuhashilab/2020_TEDxdesign#17]
TEDx会場デザインの進捗状況報告場所

**Comment by AtsukoWakamatsu** [comment]
## styly MTG　 7/21(火)15:00~
### 参加者
stylyエンジニア　空間デザイン部・ものづくり部・おうだい・さち
### 会場設計のイメージ
・stylyを利用して会場設計
・MR空間のなかでスピーチを行ってもらう
・スピーカーの方は後撮りで合成する
・仮面ライダー空間＋スピーカーに1人につき1ステージ
・撮影方法を工夫しながらその場にいるような雰囲気を作りたい
・パワーポイントを使用しない、新しいプレゼンテーションスタイル
・
仮面ライダー空間
<img width="1227" alt="スクリーンショット 2020-07-23 0 29 00" src="https://user-images.githubusercontent.com/40018174/88197163-0c720a00-cc7d-11ea-83d4-370593d64b73.png">

### stylyの方からのコメント
stylyについて
・stylyは作品のプラットホームであるため、リアルタイムのインタラクションに向いていない
・基本的に作品のVRやMRの体験は1人で行うもの
・撮影可能　AR、VRのみ
### TEDx会場について
#### MRの場合
* MR空間の撮影ができないため、人をMR空間に立たせることができない。
* MR空間のなかに人を投影するのはかなり難しい
→①MR空間のなかにグリーンバック、クロマキー合成　ただし定点カメラ
→[LIV](https://liv.tv/)や[OBSstudio](https://obsproject.com/ja)などの配信用softwareを駆使する必要あり
→②作成したMR空間の中にスピーチの様子を動画で載っける　二次元　一番簡単
#### ARの場合
* 会場が必要にはなるが、blender、Unityのアニメーション機能、時間設定を利用すればパワポを利用しないプレゼンテーションが可能。
* ただし撮影がstylyのアプリをインストールできるIOS,Andorid端末に限られる。
* カメラワーク次第では臨場感を出すことができるのでは？
#### VRの場合
* 撮影可能
* スピーカーを置くことができない アバターが必要になる

#### 字幕について
* 字幕はunityで組む
* 撮影したものに後から動画編集で字幕を加える
* リアルタイムの字幕　→OBS　
#### styly重い問題
* pcのスペックにかなり差が出る
* 理想はgaming　PCであれば基本的に問題なし
### 問題点
* 想像していた会場設計ができないと言われてしまった
* MR空間を諦めるのか、またstylyでの会場設計のままで話を進めるのかを検討する必要あり。
* blender、Unityに詳しい人が多くない...

**Comment by AtsukoWakamatsu** [comment]
## ハッカソンMTG＃１  7/22(水) 22:00~
###  参加者
れん、あやか、あつこ、ばびー、神田
### 方針
* MR空間を諦めたくない
* スピーカーがアバターになってしまうことは避けたい→VR空間は×
* AR空間　会場が決まっていない状態でやるの難しい　
* MR空間でどこまでできるのかやってみる
* OBSは今回後回し
*Unity　ハッカソンの内にやっておきたい？
### 目標
[理想図](https://youtu.be/mh69v7Yh1YY?t=50)

### ハッカソン内容
* ６月のハッカソンで作成したstylyの空間にクロマキー合成をしてみる
→YouTubeに乗っているグリーンバックの動画を利用する
* ６月のハッカソンで作成したstylyの空間にTEDxの動画を埋め込む
* TEDxメンバーにgithubを理解してもらう

**Comment by AtsukoWakamatsu** [comment]
## ハッカソンMTG ＃２　7/24(金)21:00~
### 参加者
はる、バビー、神田、あやか、あつこ、さほちゃん

## 内容
### ＃候補案① MR×動画
MR空間にtedxの動画を埋め込む　#13 
<img width="300" alt="スクリーンショット 2020-07-24 19 11 00" src="https://user-images.githubusercontent.com/40018174/88396376-6b5e8d00-cdfd-11ea-8495-96d2672f6add.png">
・空間の背景色とスピーカーの背景色が同じだとそこまで違和感がないのでは？
・空間に対して動画を大きくして映画館みたいにする
・ジャイロを使えたらいい
・OBSは必要
・背景を360度カメラにして、後づけでポンとオブジェクトを出すことはできる？
**・動画自体はstylyのARで撮影したものを流す？（要検討）**
▶︎問題点
→動画止まらない、永遠ループしちゃう
→司会者の立ち位置
→スピーカーと司会者の切り替え方法
### ＃候補案② spacely
[spacely ](https://spacely.co.jp/projects/16098)
・一番初めにイメージしていたバブル空間を作ることが可能？
→課金必要そう
→移動した空間に動画を貼っておくのあり。
→OBSの利用はマスト

### # 候補案③ VR空間
* cluster　#16 
→観客反応しやすい
→配信しやすい
→容量重い
→アバター作る必要あり
*  [VR Chat](https://www.youtube.com/watch?v=IXdpjC7NHWc&feature=youtu.be)
→人が結構リアル
→VR専用機器が必要
→人を動くようになるには blender/Unityで骨組みいれる

### リアルタイムの反応は必要か(要検討)
・”スピーカーが話す場”であるためコメントはいらない
・拍手など観客側が反応ができる機能は欲しい
・スピーカーの方も観客の反応が見れたほうが嬉しいのでは...

### 高田先生から候補案
1. リアルタイムで後から編集して動画配信　→　[URL](https://m.youtube.com/watch?v=Ac5MwC1FF0g)
2. 360度カメラ　機材コンテンツにもよる、動画配信△？　→　[URL](https://youtu.be/-aHHSxCh0c8)

### 決定事項
* 明日までにクロマキーにするとどのようになるのかを確認　byバビー、れん
* あやかはグラレコ担当
* styly渡邊さん、YORIMIYAさん、古橋先生を交えてmtgを行う必要あり。（りさちゃんから）
* 丸山さん（情テク2年）とのmtgで会場設計方針を完全決定する

**Comment by Babby168** [comment]
## [Spacely](https://spacely.co.jp/)
https://youtu.be/8jL4K851oJU

・企業、ビジネス向け感が強い
・パノラマ写真を撮ってクラウドにアップロードする
・様々なデバイスで見れる（iPhone, iPad, PC,  VRヘッドセット）
・PC、スマホで制作、編集、管理するクラウドソフト
・アクセス分析機能あり

**Comment by Babby168** [comment]
## クロマキー合成
クロマキー合成に適した（やりやすい）編集ソフト

### [Filmora](https://filmora.wondershare.jp/video-editor/)
・[無料体験版](https://filmora.wondershare.jp/faq/before-purchase/#%E8%A3%BD%E5%93%81%E7%89%88%E3%81%A8%E4%BD%93%E9%A8%93%E7%89%88%E3%81%AE%E9%81%95%E3%81%84%E3%82%92%E6%95%99%E3%81%88%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84)があるが、動画にロゴの表示が勝手についてしまう。
・初心者でも比較的に編集可能
・背景を自由に変えられる合成モードが搭載
・テンプレの特殊効果を挿入可能

### [Video Pad](https://www.nchsoftware.com/videopad/jp/index.html)
・無料版あり
・音声の挿入、編集可能
・３D動画、360°動画の編集に対応
・著作権フリーの効果音や音楽をダウンロードできる音声ライブラリ搭載
・[クロマキーの使い方](https://www.nchsoftware.com/videopad/jp/kb/1408.html)

###  [AviUtl](https://aviutl.info/intro/)


### [AfterEffects](https://www.adobe.com/jp/products/aftereffects.html)
・Adobeのソフトが故にAdobe所持者でないと有料
（・Adobeのソフトだと180度VRと360度VRを編集可能）[説明ページ](https://www.adobe.com/jp/creativecloud/video/virtual-reality.html)
（・[360度VRビデオの編集](https://helpx.adobe.com/jp/premiere-pro/how-to/edit-360-vr-video.html?promoid=DW3G15JT&mv=other)）
（・[Adobe After Effectsプロジェクトから360度ビデオを作成する方法](https://helpx.adobe.com/jp/after-effects/how-to/create-360-video.html)）

**Comment by AtsukoWakamatsu** [comment]
## ハッカソンMTG＃３　7/25 23:00~
### 参加者
古橋先生、丸山さん、りさちゃん、ものづくり部、空間デザイン部
### 丸山さんから
現在のイメージを形にする方法は３つ
1. 映画用のモーションキャプチャー
バイコン？専用スタジオ、専用のスーツを着て撮影
多額な費用
2. VR Chatのアバター利用
・hmd（ヘッドマウントディスプレイ）をつけて話し、モーションを加える
・それをアバター化
3. 360度カメラで撮影
・360度カメラさえあれば◎
・グリーンバックで撮影してその後空間の中に合成することはできる
・Unityを利用し、台本用意してスピーカーの方と打ち合わせを行えばパワポを使わないプレゼンも可能

8月下旬からオンラインで参加可能

### 360度カメラを利用する→仮決定
・グリーンバック
→ブルーシートのグリーンver [2000円程度](https://www.monotaro.com/p/6935/9054/?utm_medium=cpc&utm_source=Adwords&utm_campaign=246-833-4061_6466659573&utm_content=77481175356&utm_term=_380604218787__aud-907170561978:pla-326727104138&gclid)で購入可能　コスパが一番いい
・stylyで合成
→[記事](https://styly.cc/ja/tips/styly-360movie-import)にもあるように合成は可能
→人が伸びたりしないか、どうやって見えるのか（画質）はやってみないとわからない
・clusterで合成
→360度カメラ設置可能だと思われる？
→clusterの良さを殺してるのでは
→どうやって見えるかわからない
→個人でのワールドの遷移ができない？（不確）のでclusterの方に話を聞く必要あり
・合成した後にUnityを利用してオブジェクトをスピーカーに合わせて動かすこと可能

### 古橋先生から
・360度カメラ ２つ(RICOH THETA,?)持っている
・360度カメラをみんな利用したことない、知識ゼロから始めるのは結構大変
・早めにプロに聞いて動く→styly、clusterの方へ直接相談
・短期集中型でガッツリやるのがいい→9月3,4日@長野　
・**9月までは様々な方法を試す、オンラインイベントに参加して方法を盗む**

### りさちゃんから
・観客とスピーカー、司会者とスピーカーとの交流を大事にしたい
・TEDx側から会場制作へのお金は出せない

### 決定事項
・360度カメラを利用する
・観客との交流＞会場のクオリティの高さ
・配信プラットフォームは未決定
・7/31　14:00~　360度カメラの説明会 @調布SARA＋
・スピーカーの方への質問内容の変更なし

### 今後の検討事項
・STYLY or Cluster？
・画質どうなるか
・動画の配信方法　cluster、zoom、YouTubeなど
・観客と交流方法

### 参考資料　
目を通しておいてください！
・[360度ビデオの撮影方法](https://helpx.adobe.com/jp/after-effects/how-to/create-360-video.html)
・[360度VRビデオの編集方法](https://helpx.adobe.com/jp/premiere-pro/how-to/edit-360-vr-video.html?promoid=DW3G15JT&mv=other)
・[360度カメラの仕組み](https://jp.ricoh.com/technology/tech/065_theta)

**Comment by AtsukoWakamatsu** [comment]
## 360°カメラ 体験会　7/31 14:00~ 
### 参加者
古橋先生、れん、ばびー、あつこ

### 360度カメラの仕組み　古橋先生より
![IMG_9574](https://user-images.githubusercontent.com/40018174/89056849-a3367900-d397-11ea-8025-fb2a541b3f6a.JPG)
360度カメラは基本的に表裏にレンズが２つ　
2つのカメラがそれぞれ180度ずつ撮影してデータ化
↓
カメラの中に保存される時は左図のように長方形の中に円が2つ保存される
↓
専用のスマホアプリを使用することでエクイレクタングラー図法の形に変換可能
↓
**equirectangular（エクイレクタングラー）図法**とは360°の画像を平面にすること
縦横比は1:2
この形に変えることでYouTubeやFacebookなどアップロード可能になる

### カメラの種類
#### ・[RICOH THETA S](https://theta360.com/ja/about/theta/s.html)　ばびー担当
* 2.7K　
* 撮影中の充電できない
* 給電が必要　
* 運用めんどい
* SDカード使えない、内臓のみ

#### ・[kandao QOOCAM 8k ](https://www.kandaovr.com/ja/qoocam-8k/)
* 古橋先生一番使いやすい
* 8k30fps
* 露出の変更可能
* 充電しながらの撮影

#### ・[kandao QOOCAM　](https://www.kandaovr.com/ja/qoocam/)れん担当
* カメラのボディを90度に曲げること可能
* 長時間の撮影はリスクある
*１、２時間で熱を持つ　熱対策必要
* 高解像度パノラマ　
* wifi
#### ・[ insta360 one/ nano](https://www.ask-corp.jp/products/insta360/)　あつこ担当
* iPhoneのコネクタ有　
* streaming 簡単　
* WiFiを占有しない　
* ライブは有線で利用可能
* 手軽
### 360度カメラの利用方針
1. stylyで作成した空間＋クロマキー合成
→前回のハッカソンと同じ

2. 360°カメラで撮影したものをstylyに埋め込む＋TEDxのロゴ＋クロマキー合成
→撮影したものをYouTubeにあげてstylyにあげる
→stylyでオブジェクト追加
→そこにグリーンバックのクロマキー合成
* 代案
スピーカー自身に撮影をお願い
360°カメラをスピーカーの人に郵送でカメラ送って撮影してもらう　
（スピーカーにゆかりのある場所を使いたい場合のみ）

3. 360°カメラ撮影の空間とstylyの空間を途中で切り替え
→360°カメラの空間と作成したstylyの空間をスピーカーの求めるタイミングで切り替えてみる

4. 司会者の背景として利用？
→ 青学にゆかりのある人なので青キャン、サガキャン、チャペルなど撮影
→ 司会者の背景用にいくつか用意する

### 360°カメラで試してみること
動画を撮影（円形状）→専用アプリを利用、保存（エクレタンギュラ）→YouTubeで共有→stylyに埋め込む
* 撮影方法をいろいろ挑戦
* アップロード時間はどのくらい？
* YouTubeにアップどのくらい？
* TEDxのオブジェクトを入れたstylyに埋め込んだのを送る
* 長時間ver /  短時間ver
* 手持ち、三脚どんな感じ？
* 音の感じ、感想を送る

### 合宿までにやること
 *  撮影したものをアップロードしてどのようになるのかを確認→共有→MTG 
 * スピーカーの撮影自体はまだできない　
 * キャンパスでコロナの影響見ながら撮影？
 * スピーカー撮影用カメラ貸してくれる人募集
 * グリーンバック用のシート
 * stylyの方に連絡、360度カメラ
### 合宿でやること
360度カメラの映像＋クロマキー合成映像（＋OBS配信）
* 撮影機材、撮影方法の確認
* kuniharuに練習用の撮影用のカメラで撮影　２台体制　
* 撮影した映像を360度カメラと合成
* youtubeにアップロードする　

### 決定事項
* オンラインチームは全員styly、クロマキー合成できる必要ある
* れん、ばびー、あつこはそれぞれの360°カメラの音質画質などレビュー、報告を行う
* 配信方法、obsは合宿以降で
* 神田は配信研究する
