### ISSUE TITLE
6月　ハッカソン　仮会場

### ISSUE THREAD

**Issue by AtsukoWakamatsu** [furuhashilab/2020_TEDxdesign#2]
若松作
[styly URL](https://gallery.styly.cc/scene/d0b180b0-4c53-400c-ad36-62933d150862)
<img width="1219" alt="スクリーンショット 2020-06-30 18 44 41" src="https://user-images.githubusercontent.com/40018174/86111481-c43e4c80-bb01-11ea-9588-6c23a614ddcd.png">

**Comment by Ayaka0324** [comment]
川嶋作
[styly URL](https://gallery.styly.cc/scene/b06e2384-6e8a-47ce-8da6-afa904f31af3)
<img width="1440" alt="スクリーンショット 2020-06-30 19 01 29" src="https://user-images.githubusercontent.com/62421184/86113390-2ac46a00-bb04-11ea-8b82-fce2de3a865c.png">

**Comment by rensanrenren** [comment]
れん作
[styly url](https://gallery.styly.cc/scene/91c5a55b-422a-450e-a6b4-da533fc19765)
![slack-imgs](https://user-images.githubusercontent.com/49857703/86112865-7a566600-bb03-11ea-8148-dfd2b23dd5f6.jpg)

**Comment by hharumax12** [comment]
[はる作]
https://gallery.styly.cc/scene/689de1f3-3769-4994-87b2-596105969567


![image](https://user-images.githubusercontent.com/41771776/86115094-6a8c5100-bb06-11ea-87cf-d77e94f27f88.png)

**Comment by Babby168** [comment]
馬場作
[Styly URL](https://gallery.styly.cc/scene/22e1713a-d7eb-480e-9a1c-124396f1cb94)

![image](https://user-images.githubusercontent.com/40033443/86122478-e1c7e200-bb12-11ea-9154-21fdb4e384e2.png)

**Comment by Babby168** [comment]
馬場作
## イメージ動画

![2020-07-08 (3)](https://user-images.githubusercontent.com/40033443/86895333-48668480-c13f-11ea-8dc5-00dd3a2e96d7.png)

![2020-07-08 (2)](https://user-images.githubusercontent.com/40033443/86895352-4ef4fc00-c13f-11ea-89f7-9db73821050c.png)


[BABBY-prototype-stage-video.zip](https://github.com/furuhashilab/2020_TEDxdesign/files/4889346/BABBY-prototype-stage-video.zip)
