### ISSUE TITLE
Gatsby.JS のいけてるテンプレートを選ぶ！

### ISSUE THREAD

**Issue by mapconcierge** [furuhashilab/2020_TEDxdesign#31]
ここからどれか選んで！
https://www.gatsbyjs.com/starters/?v=2

**Comment by SahoYoshihara** [comment]
自分は下の二つのように最初に写真が大きく貼られているやつがいいと思います！
* https://www.gatsbyjs.com/starters/rohitguptab/rg-portfolio/
（https://rg-portfolio.netlify.app）

* https://www.gatsbyjs.com/starters/himali-patel/MyClicks
（https://myclicks.netlify.app）

**Comment by mapconcierge** [comment]
@Babby168 はどう思う？

**Comment by mapconcierge** [comment]
個人的には https://rg-portfolio.netlify.app/ のほうかな

myclicksのほうは、ゆるふわな雰囲気で、TEDx のような硬いイメージには合わないように思える。

**Comment by Babby168** [comment]
https://www.gatsbyjs.com/starters/codebushi/gatsby-starter-dimension

このような感じのはどーでしょう。

**Comment by Babby168** [comment]
あとは、
https://www.gatsbyjs.com/starters/thundermiracle/gatsby-startbootstrap-agency
で硬いイメージも持ちつつ、スタイリッシュな感じでいくのも、

**Comment by Babby168** [comment]
https://www.gatsbyjs.com/starters/akzhy/gatsby-starter-elemental

それかこのようにちょっとアーティスティックな要素の強いのも良いのではないかと

**Comment by SahoYoshihara** [comment]
@Babby168 
https://www.gatsbyjs.com/starters/codebushi/gatsby-starter-dimension
↑デザインもクールでいいですね！これにした場合、随時載せるお知らせやスピーカーを紹介するブログのようなものを追加することは可能なのでしょうか？

https://www.gatsbyjs.com/starters/thundermiracle/gatsby-startbootstrap-agency
↑こちらはTedxAGUを知らない人でも読みやすいスタイルになっていると思うので、HPとしての機能性も十分にいいと思います！

**Comment by SahoYoshihara** [comment]
自分としては、HPに入ってすぐにチケット販売の目印を示した方がお客さんもチケットを購入しやすいと思うので、https://www.gatsbyjs.com/starters/akzhy/gatsby-starter-elemental
こちらのデザインにあるHome画面の「See Works→」の機能を他のデザインの場合でも採用したいです。

**Comment by Babby168** [comment]
https://www.gatsbyjs.com/starters/codebushi/gatsby-starter-dimension
これ自分で挙げといてあれだけど、機能面でみたら微妙だなw

**Comment by Babby168** [comment]
https://www.gatsbyjs.com/starters/akzhy/gatsby-starter-elemental
@SahoYoshihara 
その案はめっちゃ良いね！

**Comment by SahoYoshihara** [comment]
@Babby168 ありがとうございます！
個人的には、
https://www.gatsbyjs.com/starters/himali-patel/MyClicks

https://www.gatsbyjs.com/starters/thundermiracle/gatsby-startbootstrap-agency

この二つのうちどちらかを選び、チケット購入先案内の機能（https://www.gatsbyjs.com/starters/akzhy/gatsby-starter-elemental ）
をHome画面につけたいです。

**Comment by SahoYoshihara** [comment]
> 自分としては、HPに入ってすぐにチケット販売の目印を示した方がお客さんもチケットを購入しやすいと思うので、https://www.gatsbyjs.com/starters/akzhy/gatsby-starter-elemental
> こちらのデザインにあるHome画面の「See Works→」の機能を他のデザインの場合でも採用したいです。

**Comment by mapconcierge** [comment]
ひとつに絞る必要があるので、
最終的な結論は
https://www.gatsbyjs.com/starters/akzhy/gatsby-starter-elemental

でいくと理解しました。確かに、 TEDの雰囲気に近いね。
