### ISSUE TITLE
TEDｘAoyamaGakuinUロゴの色をSTYLY上で反映させる

### ISSUE THREAD

**Issue by AtsukoWakamatsu** [furuhashilab/2020_TEDxdesign#4]
blenderで作成した色が反映できていない

**Comment by Babby168** [comment]
## このような色が付かなく、グレーの単色のようになってしまう

![image](https://user-images.githubusercontent.com/40033443/86312384-8a825880-bc5d-11ea-982f-64310ba5062b.png)

**Comment by Babby168** [comment]
## STYLY助け合い所で解決完了！

![iOS の画像 (1)](https://user-images.githubusercontent.com/40033443/87009088-a8246480-c1ff-11ea-95e4-d024cf4b5e83.png)
