### ISSUE TITLE
BLENDER ガチャムク作成

### ISSUE THREAD

**Issue by hharumax12** [furuhashilab/2020_TEDxdesign#41]
### **トラブルを再現するためのサンプルデータとしてガチャムクのテクスチャデータを活用し、GitHub上で公開する。**

**Comment by Ayaka0324** [comment]
**ムック**

> glbデータ：https://drive.google.com/file/d/1pgmUnCX90icuYfFA1m7yv2HRd7ALuXiN/view?usp=sharing
> blenderデータ：https://drive.google.com/file/d/1idrtt-_4vIF9EwvzqTyQ8amgDHKSQD7I/view?usp=sharing
>  ダウンロードを押して下さい

blender
<img width="1440" alt="スクリーンショット 2020-09-29 23 43 49" src="https://user-images.githubusercontent.com/62421184/94838862-297f4200-0451-11eb-8699-6d596ed72c89.png">
styly
<img width="1439" alt="スクリーンショット 2020-09-29 23 45 34" src="https://user-images.githubusercontent.com/62421184/94838585-c7bed800-0450-11eb-9e57-9c556280ddcd.png">

**Comment by Ayaka0324** [comment]
**ガチャピン**
blender
![image](https://user-images.githubusercontent.com/62421184/94917452-82031d80-04eb-11eb-8c94-f7511b7c1aea.png)
styly
![image (1)](https://user-images.githubusercontent.com/62421184/94917461-87f8fe80-04eb-11eb-9b05-08a76ac199c9.png)
