### ISSUE TITLE
オブジェクトを詰めすぎると重くて動かなくなってしまう

### ISSUE THREAD

**Issue by AtsukoWakamatsu** [furuhashilab/2020_TEDxdesign#7]

**Comment by Babby168** [comment]
## ある程度、詰め込むとこの表示がされる。
![2020-07-07 (9)](https://user-images.githubusercontent.com/40033443/86783231-ff5cf480-c09a-11ea-8ff5-dd9af9b60614.png)

**Comment by Babby168** [comment]
## WebGLとは

ブラウザで、3次元CGを表示させるための標準仕様のこと。
ブラウザで3DCGを表示出来る様にするためのもの。

WebGL のコンテンツはブラウザ内で実行されるから、メモリはすべてブラウザによってブラウザ内部のメモリ空間に割り当てられることになる。

利用可能なメモリの総量は、

### ・ブラウザー
### ・OS
### ・デバイス

で大きく変わってくる可能性があり。

**Comment by Babby168** [comment]
## ロゴのマテリアル自体の容量は2MByteで大して影響していない。

![2020-07-07](https://user-images.githubusercontent.com/40033443/86784827-eb19f700-c09c-11ea-882c-b9c574a96f0d.png)

**Comment by Babby168** [comment]
# <解決策案>

## ・出来るだけデフォルトのものを使わない。
## ・自分たちで作った方が容量のサイズを抑えられる可能性あり。
## ・差し込む画像を荒くすることでファイルサイズが小さく出来るかも。
